### PR TITLE
🐞 fix: total price with discount

### LINKED ISSUE #23: Fix Total Price in Dashboard
Right now, on the dashboard still show the price before the discount so it's kinda miscalculated for the owners.
Please fix that in dashboard show total price after discount.

Image explanation :
- Dashboard currently show total 102jt for total order
- The real number is 94jt for total order (discount)

image
image

### PR DESCRIPTION
**Pull request by donisaputradev**

### CODE REVIEW

File: app/Actions/FetchProductSummariesAction.php [hunk 1]
```diff
@@ -279,6 +285,31 @@ private function generate(
             );
         }
 
+        $newBranches = [];
+        $totalDiscount = 0;
+
+        foreach ($summary['branches'] as $item) {
+            $orders = Order::query()
```
Comment (msyrl) [inline app/Actions/FetchProductSummariesAction.php]: $totalDiscountPerBranch

Comment (donisaputradev) [reply app/Actions/FetchProductSummariesAction.php]: oke sudah di perbaiki mas
